export const SECTOR_ANALYSTS = [
    {
        sector: 'Technology & IT',
        analyst: 'Arjun Mehta',
        title: 'Senior IT Analyst',
        description: 'TCS, Infosys, Wipro, HCL Tech — IT services, cloud, digital transformation.',
        icon: 'hardware-chip-outline' as const,
        color: '#3B82F6',
        bg: '#EFF6FF',
        darkBg: '#1e3a5f',
    },
    {
        sector: 'Banking & Finance',
        analyst: 'Priya Sharma',
        title: 'BFSI Analyst',
        description: 'HDFC, ICICI, SBI, Kotak — NIMs, credit growth, asset quality, RBI policy.',
        icon: 'business-outline' as const,
        color: '#10B981',
        bg: '#ECFDF5',
        darkBg: '#0f3d2e',
    },
    {
        sector: 'Healthcare & Pharma',
        analyst: 'Dr. Kavita Rao',
        title: 'Pharma Analyst',
        description: 'Sun Pharma, Dr Reddys, Cipla — US FDA, generics, hospitals, CDMO.',
        icon: 'medkit-outline' as const,
        color: '#EF4444',
        bg: '#FEF2F2',
        darkBg: '#4a1515',
    },
    {
        sector: 'Energy & Oil',
        analyst: 'Vikram Singh',
        title: 'Energy Analyst',
        description: 'Reliance, ONGC, NTPC, Adani Green — crude cycles, renewables, power.',
        icon: 'flash-outline' as const,
        color: '#F59E0B',
        bg: '#FFFBEB',
        darkBg: '#4a3000',
    },
    {
        sector: 'Consumer & FMCG',
        analyst: 'Ananya Iyer',
        title: 'Consumer Analyst',
        description: 'HUL, ITC, Nestle, D-Mart — rural demand, premiumisation, brand strength.',
        icon: 'cart-outline' as const,
        color: '#8B5CF6',
        bg: '#F5F3FF',
        darkBg: '#2e1a5f',
    },
    {
        sector: 'Auto & EV',
        analyst: 'Rohit Kapoor',
        title: 'Auto Analyst',
        description: 'Maruti, Tata Motors, M&M — OEM cycles, EV disruption, PLI schemes.',
        icon: 'car-outline' as const,
        color: '#06B6D4',
        bg: '#ECFEFF',
        darkBg: '#0a3040',
    },
    {
        sector: 'Infrastructure & Cement',
        analyst: 'Suresh Naidu',
        title: 'Infra Analyst',
        description: 'L&T, UltraTech, BHEL — capex cycles, order books, government projects.',
        icon: 'construct-outline' as const,
        color: '#F97316',
        bg: '#FFF7ED',
        darkBg: '#4a2000',
    },
    {
        sector: 'Metals & Mining',
        analyst: 'Deepak Agarwal',
        title: 'Metals Analyst',
        description: 'Tata Steel, JSW, Hindalco, Vedanta — commodity cycles, China demand.',
        icon: 'layers-outline' as const,
        color: '#6366F1',
        bg: '#EEF2FF',
        darkBg: '#1e1a4a',
    },
    {
        sector: 'Portfolio Strategy',
        analyst: 'Karan Sharma',
        title: 'Strategy Lead',
        description: 'Diversification, asset allocation, risk management, and overall portfolio health.',
        icon: 'analytics-outline' as const,
        color: '#EC4899',
        bg: '#FDF2F8',
        darkBg: '#47182a',
    },
];
